name: Build & Deploy to Hostinger (FTPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Create version file
        run: echo "build=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/version.txt

      - name: Verify dist/
        run: |
          if [ ! -d dist ]; then
            echo "ERRO dist nao gerado"
            exit 1
          fi
          ls -la dist

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via lftp (espelhamento)
        env:
          HOST: ${{ secrets.FTP_SERVER }}      # ex.: ftp.copypriceprofx.site (ou 147.93.14.207)
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
          DIR:  ${{ secrets.FTP_DIR }}         # ex.: public_html/
          PORT: ${{ secrets.FTP_PORT }}
        run: |
          : "${PORT:=21}"
          : "${DIR:=public_html/}"

          cat > deploy.lftp <<EOF
          set ftp:ssl-force true
          set ftp:ssl-allow true
          set ftp:passive-mode true
          set ssl:verify-certificate no
          set net:timeout 40
          set net:max-retries 3
          set net:persist-retries 2

          open -u "${USER}","${PASS}" -p "${PORT}" "${HOST}"
          mirror --reverse --delete --verbose "dist" "${DIR}"
          bye
          EOF

          lftp -f deploy.lftp

      - name: Print check URL
        run: echo "Abra https://copypriceprofx.site/version.txt para validar o deploy"
