name: Build & Deploy to Hostinger (FTPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Prova de vida do deploy
      - name: Create version file
        run: echo "build=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/version.txt

      - name: Verify dist/
        run: |
          ls -la dist || (echo "ERRO: pasta dist/ não encontrada" && exit 1)

      # Debug: lista pasta remota (com FTPS e relax de cert p/ evitar erro CN)
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Remote PWD & LIST (FTPS) - debug
        env:
          HOST: ${{ secrets.FTP_SERVER }}
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
          DIR:  ${{ secrets.FTP_DIR }}
        run: |
          echo "Conectando e listando diretório remoto..."
          lftp -e "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate no;   # ignora CN mismatch se o host não casar
            set net:max-retries 2;
            set net:timeout 20;
            open -u $USER,$PASS $HOST;
            pwd;
            cd $DIR;
            pwd;
            ls -la;
            bye
          "

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}        # ex.: ftp.copypriceprofx.site
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/                       # precisa terminar com /
          server-dir: ${{ secrets.FTP_DIR }}       # precisa terminar com /
          security: loose                          # evita erro de certificado no FTPS
          timeout: 600000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/vite.config.ts
            **/tsconfig*.json

      # OPCIONAL: limpar pasta remota antes de subir (cuidado!)
      # - name: Clean & Upload (dangerous)
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     protocol: ftps
      #     port: 21
      #     local-dir: ./dist/
      #     server-dir: ${{ secrets.FTP_DIR }}
      #     dangerous-clean-slate: true
