name: Deploy to Hostinger (FTP)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (CI)
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp          # se preferir FTPS: mude para "ftps"
          port: 21
          local-dir: dist        # envia só a pasta buildada
          server-dir: ${{ secrets.FTP_DIR }}
          # Exclui arquivos do build que não fazem sentido enviar
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
