name: Build & Deploy to Hostinger (FTPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Create version file
        run: echo "build=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/version.txt

      - name: Verify dist/
        run: ls -la dist || (echo "ERRO: dist/ não gerado" && exit 1)

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via lftp mirror (tolerante)
        env:
          HOST: ${{ secrets.FTP_SERVER }}   # ex.: ftp.copypriceprofx.site ou 147.93.14.207
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
          DIR:  ${{ secrets.FTP_DIR }}      # ex.: public_html/
          PORT: ${{ secrets.FTP_PORT || 21 }}
        run: |
          lftp -c "
            set ftp:ssl-force true;
            set ftp:passive-mode true;
            set ssl:verify-certificate no;
            set net:timeout 40;
            set net:max-retries 3;
            set net:persist-retries 2;
            open -u ${USER},${PASS} -p ${PORT} ${HOST};
            mirror --reverse --delete --verbose dist ${DIR};
            bye
          "

      - name: Print check URL
        run: echo "Abra https://copypriceprofx.site/version.txt para validar o deploy"
