name: Build & Deploy to Hostinger (FTPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Prova de vida do deploy
      - name: Create version file
        run: echo "build=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/version.txt

      - name: Verify dist/
        run: ls -la dist || (echo "ERRO: dist/ n찾o gerado" && exit 1)

      # DEBUG: lista remoto (n찾o falha se o cert n찾o casar)
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Remote PWD & LIST (FTPS) - debug
        continue-on-error: true
        env:
          HOST: ${{ secrets.FTP_SERVER }}
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
          DIR:  ${{ secrets.FTP_DIR }}
        run: |
          echo "Conectando e listando diret처rio remoto..."
          lftp -e "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate no;   # ignora CN mismatch
            set net:max-retries 2;
            set net:timeout 20;
            open -u $USER,$PASS $HOST;
            pwd;
            cd $DIR;
            pwd;
            ls -la;
            bye
          "

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}     # ex.: ftp.copypriceprofx.site
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/                   # <- barra final
          server-dir: ${{ secrets.FTP_DIR }}   # <- barra final
          security: loose                      # tolera cert diferente do host
          timeout: 600000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/vite.config.ts
            **/tsconfig*.json
