# 6) Upload via lftp (lento/robusto) + fallback
- name: Upload via lftp mirror (tolerante)
  env:
    HOST: ${{ secrets.FTP_SERVER }}      # ex.: ftp.copypriceprofx.site  (ou ftpupload.net)
    USER: ${{ secrets.FTP_USERNAME }}
    PASS: ${{ secrets.FTP_PASSWORD }}
    DIR:  ${{ secrets.FTP_DIR }}         # ex.: public_html/
  run: |
    sudo apt-get update && sudo apt-get install -y lftp

    # Tenta por até 25 minutos
    set -e
    timeout 25m lftp -c "
      set cmd:fail-exit yes;
      set ftp:ssl-force true;
      set ftp:ssl-protect-data true;
      set ftp:passive-mode true;
      set ssl:verify-certificate no;

      # timeouts/intervalos mais folgados
      set net:timeout 40;
      set net:max-retries 1;
      set net:reconnect-interval-base 5;
      set net:reconnect-interval-multiplier 1;
      set net:reconnect-interval-max 10;

      set ftp:sync-mode off;
      set xfer:clobber on;
      set xfer:use-temp-name no;

      open -u $USER,$PASS $HOST;
      cd $DIR;

      # Paralelismo conservador (se der 421/limite de conexões, deixe 1 mesmo)
      mirror -R --only-newer --ignore-time --verbose \
             --parallel=1 \
             --exclude-glob .git* \
             --exclude-glob node_modules \
             ./dist .;

      bye
    " || echo 'LFTP falhou/expirou – vamos tentar o fallback'
  continue-on-error: true

- name: Fallback upload (SamKirkland)
  if: failure()
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    protocol: ftps
    port: 21
    local-dir: ./dist/
    server-dir: ${{ secrets.FTP_DIR }}     # public_html/
    security: loose
    timeout: 900000                        # 15 minutos
    log-level: verbose
    # dangerous-clean-slate: true          # NÃO habilitar a menos que queira APAGAR TUDO antes de enviar
